export const REDIS_CHANNEL_ORDER_UPDATES = "order-updates";

export const REDIS_STRING_ORDER_CREATED = "ORDER_CREATED";
export const REDIS_STRING_ORDER_PAID = "ORDER_PAID";
export const REDIS_STRING_ORDER_CANCELLED = "ORDER_CANCELLED";
export const REDIS_STRING_ORDER_REFUNDED = "ORDER_REFUNDED";
